# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "boxen-module-maker"
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter M Souter"]
  s.date = "2013-04-15"
  s.description = "Get your boxen modules up and running easily"
  s.email = "p.morsou@gmail.com"
  s.executables = ["boxen-module-maker"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "bin/boxen-module-maker",
    "boxen-module-maker.gemspec",
    "lib/boxen-module-maker.rb",
    "lib/boxen-module-maker/bin.rb",
    "lib/boxen-module-maker/version.rb",
    "spec/boxen-module-maker_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/petems/boxen-module-maker/"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Tool to make new boxen modules easily"
end

