# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{boxen-module-maker}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter M Souter"]
  s.date = %q{2013-04-15}
  s.default_executable = %q{boxen-module-maker}
  s.description = %q{Get your boxen modules up and running easily}
  s.email = %q{p.morsou@gmail.com}
  s.executables = ["boxen-module-maker"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "bin/boxen-module-maker",
    "boxen-module-maker.gemspec",
    "lib/boxen-module-maker.rb",
    "lib/boxen-module-maker/bin.rb",
    "lib/boxen-module-maker/version.rb",
    "spec/boxen-module-maker_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{https://github.com/petems/boxen-module-maker/}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Tool to make new boxen modules easily}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

